#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: 25
#
#development:
#  <<: *default
#  database: battleship_development
#  username: postgres
#  password: postgres
#
#test:
#  <<: *default
#  database: battleship_test

development:
  adapter: mysql2
  encoding: utf8
  database: battle_ship
  username: battle_ship
  host: localhost
  pool: 5
  port: 5432
  password: mak123654789