default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 25

development:
  <<: *default
  database: battleship_development

test:
  <<: *default
  database: battleship_test